[project]
name = "developing-technical-skills-for-working-with-the-marimo-notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.20.2",
    "pandas>=3.0.1",
    "polars>=1.38.1",
]
